name: Simple CI/CD with Delta Deploy

on:
  pull_request:
    branches: [ qa ]   # Validation on PR
  push:
    branches: [ qa ]   # Deploy after merge into QA

jobs:
  validate:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Validation
        run: |
          echo "Running validation..."
          # apne test/lint commands daalein
          # e.g. npm install && npm test

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find Delta Changes
        run: |
          echo "Finding delta changes..."
          git fetch origin
          # Compare last commit with previous one
          git diff --name-only HEAD~1 HEAD > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

      - name: Deploy Delta
        run: |
          echo "Deploying only delta changes..."
          while read file; do
            echo "Deploying $file"
            # yahan apna deploy logic daalein per file basis
            # e.g. scp $file server:/app/
          done < changed_files.txt