name: Salesforce CI/CD - Auth URL Based Deploy

on:
  pull_request:
    branches: [ qa ]     # Validate on PR
  push:
    branches: [ qa ]     # Deploy on merge

jobs:
  validate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate to Salesforce (Auth URL)
        run: |
          echo "${{ secrets.SFDX_AUTH_URL_QA }}" > authurl.txt
          sf org login sfdx-url \
            --sfdx-url-file authurl.txt \
            --alias QA

      - name: Validate Deployment
        run: |
          sf project deploy validate \
            --source-dir force-app \
            --test-level NoTestRun

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate to Salesforce (Auth URL)
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > authurl.txt
          sf org login sfdx-url \
            --sfdx-url-file authurl.txt \
            --alias QA

      - name: Deploy to QA
        run: |
          sf project deploy start \
            --source-dir force-app \
            --test-level NoTestRun
